<a href="https://colab.research.google.com/github/cesargar1507/DatasetsUB/blob/main/M3_AI2_GarciaCesar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [104]:
!pip install cssselect
from urllib.request import Request
from bs4 import BeautifulSoup
from lxml import html
from urllib.request import urlopen
import pandas as pd

Requirement already satisfied: cssselect in /usr/local/lib/python3.10/dist-packages (1.2.0)

**Selector CSS**

**Nombre:** li.ipc-metadata-list-summary-item h3.ipc-title__text

**Rating:** li.ipc-metadata-list-summary-item span.ipc-rating-star--imdb

**Votos:** li.ipc-metadata-list-summary-item div.sc-d80c3c78-0.jPoaKS

La parte común es li.ipc-metadata-list-summary-item

In [105]:
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
headers = {'User-Agent': user_agent}
url = "https://www.imdb.com/search/title/?genres=comedy&languages=es"
request = Request(url, None, headers) # la nueva cabecera y url en conjunto
url_imdb = urlopen(request)
html_content = url_imdb.read()

# Construir el árbol de nodos
tree = html.document_fromstring(html_content)

# Realizar la consulta CSS
resultado = tree.cssselect("li.ipc-metadata-list-summary-item")

print('Número de elementos:')
print(len(resultado))

Número de elementos:
50

In [111]:
peliculas = []

for peli in resultado:
    # Busqueda de los elementos de cada pelicula
    resultado_nombre = peli.cssselect("h3.ipc-title__text")
    resultado_rating = peli.cssselect("span.ipc-rating-star--imdb")
    resultado_votos = peli.cssselect("div.sc-d80c3c78-0.jPoaKS")

 # Verifica que longitud de cada elemento sea > 0 para almacenar el contenido o None
    nombre = resultado_nombre[0].text_content().split(".")[1].strip() if resultado_nombre else None
    rating = resultado_rating[0].text_content().split("(")[0].strip() if resultado_rating else None
    votos = resultado_votos[0].text_content().split("Votes")[1].strip() if resultado_votos else None

    # Construye diccionario de una pelicula
    pelicula = {
        "Nombre": nombre,
        "Rating_IMDB": rating,
        "Votos": votos
    }

    # Utiliza append para acumular las peliculas
    peliculas.append(pelicula)

    # Detener el bucle después de recolectar 50 películas
    if len(peliculas) >= 50:
        break

# Convierte el listado de diccionario en un DataFrame de pandas
df_peliculas = pd.DataFrame(peliculas)
df_peliculas_styled = df_peliculas.style.set_properties(**{'text-align': 'left'}) \
    .set_table_styles([{'selector': 'th', 'props': [('text-align', 'left')]}])
df_peliculas_styled