<a href="https://colab.research.google.com/github/cesargar1507/DatasetsUB/blob/main/M3_AI2_GarciaCesar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!pip install cssselect
from urllib.request import Request
from bs4 import BeautifulSoup
from lxml import html
from urllib.request import urlopen
import pandas as pd

Requirement already satisfied: cssselect in /usr/local/lib/python3.10/dist-packages (1.2.0)

In [8]:
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
headers = {'User-Agent': user_agent}
url = "https://www.imdb.com/search/title/?genres=comedy&languages=es"
request = Request(url, None, headers)
url_imdb = urlopen(request)
html_content = url_imdb.read()

tree = html.document_fromstring(html_content)

resultado = tree.cssselect("li.ipc-metadata-list-summary-item")

print('Número de elementos:')
print(len(resultado))

Número de elementos:
50

In [9]:
peliculas = []

for peli in resultado:
    resultado_nombre = peli.cssselect("h3.ipc-title__text")
    resultado_rating = peli.cssselect("span.ipc-rating-star--imdb")
    resultado_votos = peli.cssselect("div.sc-d80c3c78-0.jPoaKS")

    nombre = resultado_nombre[0].text_content().split(".")[1].strip() if resultado_nombre else None
    rating = resultado_rating[0].text_content().split("(")[0].strip() if resultado_rating else None
    votos = resultado_votos[0].text_content().split("Votes")[1].strip() if resultado_votos else None

    pelicula = {
        "Nombre": nombre,
        "Rating_IMDB": rating,
        "Votos": votos
    }

    peliculas.append(pelicula)

    if len(peliculas) >= 50:
        break

df_peliculas = pd.DataFrame(peliculas)
df_peliculas_styled = df_peliculas.style.set_properties(**{'text-align': 'left'}) \
    .set_table_styles([{'selector': 'th', 'props': [('text-align', 'left')]}])
df_peliculas_styled